#!/usr/bin/env bash

# Source: https://gist.github.com/arteymix/03702e3eb05c2c161a86b49d4626d21f
# Usage: git-archive-all <git-dir> <output.tar>
function git-archive-all() {
    out=$(realpath $2)
    git -C $1 archive --output "$out" HEAD
    git -C $1 submodule foreach --recursive "git archive --prefix \$path/ --output \$sha1.tar HEAD && gtar --concatenate --file "$out" \$sha1.tar && rm \$sha1.tar"
}

git --git-dir ~/dotfiles/.git archive --output=dotfiles.tar HEAD
git --git-dir ~/.config/nvim/.git archive --output=nvim-config.tar HEAD
git-archive-all ~/.local/share/nvim/site/pack/all nvim-plugins.tar


docker build -t devc .

rm dotfiles.tar
rm nvim-config.tar
rm nvim-plugins.tar
