#!/usr/bin/env bash

set -e # Fail on first error

container=$(pwd | sed 's/\//-/g' | cut -c2- | tr '[:upper:]' '[:lower:]')

if [[ "$1" == "--init" ]]; then

    MOUNT="--mount type=bind,src=$PWD,dst=/root/pwd"

    docker rm -f $container &> /dev/null
    docker run \
        -it \
        $MOUNT \
        --name $container \
        devc bash
    exit 0
fi

docker start -i $container
