#!/usr/bin/env bash

set -e # Fail on first error

# Make a new container
function new() {
    pwd_basename=$(basename "$PWD")
    docker rm -f $1 &> /dev/null
    docker run \
        -it \
        --mount type=bind,src=$PWD,dst=/root/$pwd_basename \
        --name $1 \
        -w /root/$pwd_basename \
        devc bash
}

# Resume an existing container
function resume() {
    docker start -i $1
}

container=$(pwd | sed 's/\//-/g' | cut -c2- | tr '[:upper:]' '[:lower:]')

if [[ "$1" == "--init" ]] || ! docker container inspect $container &> /dev/null; then
    new $container
else
    resume $container
fi
