#!/usr/bin/env bash

# Usage: ./init <name> <mount-dir>

if [[ $# -lt 1 || $# -gt 2 ]]; then
    echo "Usage: ./init <name> <mount-dir>"
    exit 1
fi

if [[ $# -eq 2 ]]; then
    MOUNT="--mount type=bind,src="$(pwd)"/mount/$2,dst=/root/$2"
fi

docker run \
    -it \
    $MOUNT \
    --name $1 \
    nvim bash
